version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    networks:
      - micro-net

  todo-service:
    build: ./todo-service
    container_name: todo-service
    ports:
      - "3002:3002"
    networks:
      - micro-net

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - micro-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - todo-service
      - frontend
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
