name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Docker Hub Username
        run: echo "Logging into Docker Hub as: ${{ secrets.DOCKERHUB_USERNAME }}"
      
      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Build and push todo-service
        uses: docker/build-push-action@v5
        with:
          context: ./todo-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-service:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
